# Generated by Django 5.0.1 on 2024-01-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='flag',
            field=models.CharField(choices=[('Feature', 'feature'), ('Sale', 'sale'), ('New', 'new')], max_length=10, verbose_name='flag'),
        ),
    ]
