# Generated by Django 5.0.1 on 2024-01-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_quantity_alter_product_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='flag',
            field=models.CharField(choices=[('Sale', 'sale'), ('New', 'new'), ('Feature', 'feature')], max_length=10, verbose_name='flag'),
        ),
    ]
