# Generated by Django 5.0.1 on 2024-02-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_brand_slug_alter_product_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='flag',
            field=models.CharField(choices=[('Feature', 'feature'), ('New', 'new'), ('Sale', 'sale')], max_length=10, verbose_name='flag'),
        ),
    ]
