# Generated by Django 5.0.1 on 2024-02-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='flag',
            field=models.CharField(choices=[('New', 'new'), ('Sale', 'sale'), ('Feature', 'feature')], max_length=10, verbose_name='flag'),
        ),
    ]
