# Generated by Django 5.0.1 on 2024-03-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='flag',
            field=models.CharField(choices=[('Sale', 'sale'), ('Feature', 'feature'), ('New', 'new')], max_length=10, verbose_name='flag'),
        ),
    ]
