# Generated by Django 5.0.1 on 2024-06-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_product_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='flag',
            field=models.CharField(choices=[('New', 'new'), ('Feature', 'feature'), ('Sale', 'sale')], max_length=10, verbose_name='flag'),
        ),
    ]
