# Generated by Django 5.0.1 on 2024-02-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='company')),
                ('call_us', models.CharField(max_length=25)),
                ('emal_us', models.EmailField(max_length=254)),
                ('about', models.CharField(max_length=1000)),
                ('fb_link', models.URLField(blank=True, null=True)),
                ('x_link', models.URLField(blank=True, null=True)),
                ('ins_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=100)),
            ],
        ),
    ]
