# Generated by Django 5.0.1 on 2024-02-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_order_code_cart_cartdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdetail',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
